/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddItemToTab: typeof import('./src/components/userPage/AddItemToTab.vue')['default']
    ClearHistory: typeof import('./src/components/admin/User/ClearHistory.vue')['default']
    ClearTab: typeof import('./src/components/ClearTab.vue')['default']
    CustomItem: typeof import('./src/components/userPage/CustomItem.vue')['default']
    DeleteItem: typeof import('./src/components/admin/Item/DeleteItem.vue')['default']
    DeleteItemFromTab: typeof import('./src/components/userPage/DeleteItemFromTab.vue')['default']
    EditItem: typeof import('./src/components/admin/Item/EditItem.vue')['default']
    FeedBack: typeof import('./src/components/FeedBack.vue')['default']
    NewItem: typeof import('./src/components/admin/Item/NewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleRole: typeof import('./src/components/admin/User/ToggleRole.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
