version: "3.0"
services:
  firebase:
    container_name: jcstab
    build: .
    image: jcstab
    volumes:
      - /mnt/c/projects/sites/JCSTabs:/config
    ports:
      - 4400:4400
      - 4500:4500
      - 5000:5000
      - 5001:5001
      - 8001:8001
      - 8080:8080
      - 9000:9000
