name: Delete old workflow runs
on:
  schedule:
    - cron: "0 0 1 * *" # Runs at 00:00 on the 1st of every month
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 1
